### ISSUE TITLE
'GrowingCoreKit/GrowingCoreKit.h' file not found

### ISSUE THREAD

**Issue by cikichen** [growingio/flutter-growingio-track#1]
```
'GrowingCoreKit/GrowingCoreKit.h' file not found
```

![image](https://user-images.githubusercontent.com/1478821/49639236-735d9380-fa45-11e8-89fd-7701ee92c675.png)

**Comment by cikichen** [comment]
![image](https://user-images.githubusercontent.com/1478821/49639803-dac81300-fa46-11e8-806f-aec9c95af6bd.png)

**Comment by cikichen** [comment]
问题已经找到，商业项目麻烦你们自测了再发出来行吗？负点责任。

在plugin的podspec里面补上
![image](https://user-images.githubusercontent.com/1478821/49640080-90936180-fa47-11e8-887e-7a82d66bc911.png)

**Comment by music-man** [comment]
你好，'GrowingCoreKit/GrowingCoreKit.h' file not found ，是因为还需要pod我们的GrowingCoreKit ，在官网里我们都有写明 ， 我们没有加GrowingCoreKit的依赖第一点是想和Android统一，第二点我们的产品分为无埋点和埋点两种 ，我们不确定用户具体使用哪个。
官网链接 https://docs.growingio.com/docs/sdk-integration/flutter-mai-dian-sdk
