### ISSUE TITLE
下载提供的demo 在执行flutter run的时候出现以下错误

### ISSUE THREAD

**Issue by yanqiuLove** [growingio/flutter-growingio-track#2]
就算是重新创建一个新的flutter工程，按照官方文档提供的信息集成，也会报出同样的错误

<img width="500" alt="WeChatbe2e28c11ac27ed0dfcb21e4291ddc82" src="https://user-images.githubusercontent.com/19206208/59827186-95c45800-936a-11e9-9633-15ecfa23e81b.png">

**Comment by NanNanCHN** [comment]
@yanqiuLove 您好,是否安装了GrowingCoreKit?

**Comment by yanqiuLove** [comment]
你好，安装了

**Comment by yanqiuLove** [comment]
您好，我现在是新建了一个新的工程，然后在pubspec.yaml文件中只引入flutter_growingio_track: ^2.6.0，然后我按照文档执行了flutter pub get和flutter packages get 执行完之后，会在我的iOS目录下自动生成一个Podfile文件，里边内容是默认生成的，我跟您提供的demo中的Podfile文件做了对比，是一样的，然后我执行flutter run命令之后就会报文件找不到的错误

**Comment by yanqiuLove** [comment]
并且我发现，在您的demo中，Podfile文件第二行没有打开注释
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'
按照提示，第二行应该是打开的
我现在不确定我是否还需要其他地方的设置，我的cocopoads版本是1.7.2

**Comment by yanqiuLove** [comment]
我第一条提供的错误截图，是运行您提供的example工程所出现的错误，我不知道您那边的环境能否将同时example成功运行，同时我也不确定是否需要其他地方的配置。

**Comment by yanqiuLove** [comment]
您好，我想问一下，您提供的flutter资源库，是用的swift还是OC呢？我是否需要建立swift桥连接呢？

**Comment by yanqiuLove** [comment]
也会出现以下错误
![image](https://user-images.githubusercontent.com/19206208/59836837-d29a4a00-937e-11e9-9030-9696bcfaefa0.png)

**Comment by NanNanCHN** [comment]
> 您好，我现在是新建了一个新的工程，然后在pubspec.yaml文件中只引入flutter_growingio_track: ^2.6.0，然后我按照文档执行了flutter pub get和flutter packages get 执行完之后，会在我的iOS目录下自动生成一个Podfile文件，里边内容是默认生成的，我跟您提供的demo中的Podfile文件做了对比，是一样的，然后我执行flutter run命令之后就会报文件找不到的错误

@yanqiuLove 很抱歉,目前您的问题需要在flutter_growingio_track.podspec中加一句
s.dependency 'GrowingCoreKit', 然后pod install一下,这个问题 我们日后会尽快更新的;

**Comment by yanqiuLove** [comment]
好的，非常感谢~

------------------ 原始邮件 ------------------
发件人: Nico Deng <notifications@github.com>
发送时间: 2019年6月20日 20:05
收件人: growingio/flutter-growingio-track <flutter-growingio-track@noreply.github.com>
抄送: 燕秋Love510 <784725353@qq.com>, Mention <mention@noreply.github.com>
主题: 回复：[growingio/flutter-growingio-track] 下载提供的demo 在执行flutter run的时候出现以下错误 (#2)

**Comment by NanNanCHN** [comment]
已经发版2.6.1
