### ISSUE TITLE
不支持nullsafety

### ISSUE THREAD

**Issue by xxbmm-workspace** [growingio/flutter-growingio-track#5]
![20210401110754](https://user-images.githubusercontent.com/81726738/113238205-db051000-92da-11eb-86f3-0b778137f613.jpg)

**Comment by pinguo-laihouxin** [comment]
请尽快适配！

**Comment by YoloMao** [comment]
关闭此 issue，此问题于早前已修复，详细代码与集成步骤请移步 [master](https://github.com/growingio/flutter-growingio-track/tree/master) 分支
